export { default as DealDaily } from './DealDaily'
export { default as CountDown } from './CountDown'
export { default as Footer } from './Footer'
export { default as Banner } from './Banner'
export { default as BestSeller } from './BestSeller'
export { default as Sidebar } from './Sidebar'
export { default as Header } from './Header'
export { default as TopHeader } from './TopHeader'